export const ADD_DISH_TO_CART_REQUEST = 'ADD_DISH_TO_CART_REQUEST'
export const ADD_DISH_TO_CART_SUCCESS = 'ADD_DISH_TO_CART_SUCCESS'
export const ADD_DISH_TO_CART_FAILURE = 'ADD_DISH_TO_CART_FAILURE'
export const REMOVE_DISH_FROM_CART = 'REMOVE_DISH_FROM_CART'
export const CLEAR_ADD_DISH_SUCCESS = 'CLEAR_ADD_DISH_SUCCESS'
export const ADD_SHIPPING_ADDRESS_AND_PAYMENT_METHOD =
  'ADD_SHIPPING_ADDRESS_AND_PAYMENT_METHOD'

export const ADD_ORDER_REQUEST = 'ADD_ORDER_REQUEST'
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS'
export const ADD_ORDER_FAILURE = 'ADD_ORDER_FAILURE'

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAILURE = 'GET_ORDER_FAILURE'
